/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stdio.h>

int function_add(int a,int b,int c,int d);

int function_add(int a,int b,int c,int d)
{
	int sum;
	sum=a+b+c+d;
	return sum;
}
__attribute__((naked))void change_sp_to_psp(void)
{
	__asm volatile(".equ SRAM_END,(0X20000000+(128 *1024))");
	__asm volatile(".equ PSP_START,(SRAM_END-512)");
	__asm volatile("LDR R0,=PSP_START");
	__asm volatile("MSR PSP,R0");
	__asm volatile("MOV R0,0X02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");
}

void generate_exception(void)
{
	__asm volatile("SVC #0X2");

}

int main(void)
{
 change_sp_to_psp();
 int sum;
 int data=10;
 sum=function_add(1,2,3,4);
 generate_exception();
 return 0;

}

void SVC_Handler(void)
{
	printf("in svc handler \n");
}
