/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>



int main(void)
{
	//Enable the Fault
	uint32_t *pSHCSR = (uint32_t*)0xe000ed24;

	//Enable the fault
//	*pSHCSR |= (1<<18); //usage fault
	*pSHCSR |= (1<<17); //Bus fault
	*pSHCSR |= (1<<16); //Mem fault

// Lets force the processor to execute an undefined instruction

	void(*random_address)(void);
	random_address=(void*)0xe0000008;
	random_address();


	for(;;);
}


void HardFault_Handler(void)
{
	printf("Exception:Hard fault \n");
	while(1);
}
void MemManage_Handler(void)
{
	printf("Exception:Memmanage fault \n");
	while(1);
}
void BusFault_Handler(void)
{
	printf("Exception:Bus fault \n");
	while(1);
}
void UsageFault_Handler(void)
{
	printf("Exception:UsageFault \n");
while(1);
}
