/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
void DELAY()
{
	for(uint32_t i=0;i<500000;i++){

	}
}

int main(void)
{
  volatile uint32_t *AHB1ENR = (uint32_t*)0x40023830;
  volatile uint32_t *MODER =(uint32_t*)0x40020000;
  volatile uint32_t *ODR =(uint32_t*)0x40020014;

  *AHB1ENR |= 0x01;
  *MODER &=0xFFFFF3FF;
  *MODER |= (1<<10);

  while(1)
 {
  *ODR |= (1<<5);

  DELAY();

  *ODR &= ~(1<<5);

   DELAY();
  }
	return 0;
}
