/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define USART2_IRQNO 38


int main(void)
{
	uint32_t *pNVIC_ISPR1 = (uint32_t*)0xe000e204;
	uint32_t *pNVIC_ISER1 = (uint32_t*)0xe000e104;

	*pNVIC_ISPR1 |=(1<<(USART2_IRQNO%32));
	*pNVIC_ISER1 |=(1<<(USART2_IRQNO%32));


    /* Loop forever */
	for(;;);
}

void USART2_IRQHandler(void)
{
	printf("In USART2");
}

